### ISSUE TITLE
Performance improvement ideas

### ISSUE THREAD

**Issue by mrglassdanny** [mrglassdanny/moca-language-server#18]
Semantic highlighting and diagnostics can probably utilize multiple threads (moca, mocasql, groovy)

**Comment by mrglassdanny** [comment]
There are other places where sql/groovy ranges are processed independently of each other, and sometimes independently of moca -- probably opportunity here to utilize multiple threads

**Comment by dglass-longbow** [comment]
Just realized that ever since we started storing uri string in MocaCompilationResult, we no longer have to compile on hover, definition, and formatting if uri string we are about to compile matches compilation result's uri string!

I have added logic for this and it improves performance significantly in these areas. Fix will go out with next release!

**Comment by dglass-longbow** [comment]
Another obvious one is only compiling changes to file during MocaServices.didChange function.

This should increase performance exponentially, since right now we are just doing a full compile for each change.

**Comment by dglass-longbow** [comment]
Implemented ^ and it improves performance exponentially! Enhancement will go out with next release!

**Comment by dglass-longbow** [comment]
Piggybacking off of ^, we may be able to optimize diagnostic publishing by only refreshing diagnostics for the moca lang context the user is currently working in. 

NOTE: we cannot really do this for semantic highlighting due to how it works.

**Comment by dglass-longbow** [comment]
Added a ton of performance improvements over the last few releases and think this can be closed at this point!
