### ISSUE TITLE
Argument aliases not showing in Intellisense

### ISSUE THREAD

**Issue by Voodoo262** [mrglassdanny/moca-language-server#46]
Side by side comparison of VSCode versus LextEdit:
![image](https://user-images.githubusercontent.com/13515625/96478972-f208e780-11fd-11eb-8ce4-a915642b5820.png)
![image](https://user-images.githubusercontent.com/13515625/96479002-fcc37c80-11fd-11eb-8b4e-79c91f55fbea.png)

**Comment by dglass-longbow** [comment]
Hey @Voodoo262, thank you for the issue!

Currently, aliases can be found in the detail section:
![example](https://user-images.githubusercontent.com/36458190/96480827-5d53b900-1200-11eb-9daf-d74f07572471.gif)

That being said, it would probably be better to be able to get intellisense for alias instead of just seeing it in the detail section.

I think a good solution would be to add it to intellisense and then maybe have a different icon next to it to indicate clearly that it is an alias. What are your thoughts?

**Comment by Voodoo262** [comment]
@dglass-longbow I think that's a great idea

**Comment by dglass-longbow** [comment]
This is complete and will be released with next version!
